# Generated by Django 5.0.6 on 2024-07-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_picture_delete_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
