# Generated by Django 5.0.6 on 2024-07-13 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_picture_download_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='download_count',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='review',
        ),
    ]
